In [1]:
!pip install scikit-learn numpy

In [ ]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.preprocessing import OneHotEncoder, StandardScaler

import math

In [ ]:
iris = load_iris()
X = iris.data
y = iris.target.reshape(-1, 1)

print("Original Features:\n", X[:5])
print("Original Labels:\n", y[:5])

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("\nScaled Features:\n", X_scaled[:5])

encoder = OneHotEncoder(sparse_output=False)
y = encoder.fit_transform(y)

print("\nOne-Hot Encoded Labels:\n", y[:5])

print(f"Input Shape: {X.shape}")
print(f"Target Shape: {y.shape}")

Original Features:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Original Labels:
 [[0]
 [0]
 [0]
 [0]
 [0]]

Scaled Features:
 [[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]]

One-Hot Encoded Labels:
 [[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
Input Shape: (150, 4)
Target Shape: (150, 3)


In [ ]:
# Weights and Biases Initialization
L1_W = np.random.randn(4, 2)
L1_b = np.zeros((1, 2))
L2_W = np.random.randn(2, 3)
L2_b = np.zeros((1, 3))

def sigmoid(x = float):
    return 1/(1 + np.exp(-x))

def softmax(x = float):
    exp_scores = np.exp(x - np.max(x, axis=1, keepdims=True))
    return exp_scores / np.sum(exp_scores, axis=1, keepdims=True)

def forward_pass(X):
    a1 = sigmoid(np.dot(X, L1_W) + L1_b)
    a2 = softmax(np.dot(a1, L2_W) + L2_b)
    
def backward_pass(y):
    dsig = (1 - sigmoid(x))